### ISSUE TITLE
UXDI14-AndrewCoppinger_resumeDraft

### ISSUE THREAD

**Issue by andrewcoppinger** [ga-dc/outcomes#109]
[AndrewCoppinger_Resume_UXI.docx](https://github.com/ga-dc/outcomes/files/1613361/AndrewCoppinger_Resume_UXI.docx)

Cohort, UXDI14.  Andrew Coppinger

Dear Sarah Brooks,

I dragged and dropped the file of my resume here in Github.  Please let me know if there is any issue receiving it on your end.

Thank you very much.

Andrew Coppinger

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. Your resume needs to be updated to focus on your current skills and goals. You've branded yourself as a UX designer - now you've got to prove it. List UXDI in your experience and education sections, and update your list of skills. 

2. Your resume should be one page - pare down your content to the most essential points and eliminate anything extraneous to meet this standard. Be specific in noting what you accomplished in each position, and focus less on what you were responsible for.

3. Be thoughtful about your formatting. Keep it consistent (some of your position titles are in all caps, some are not) and add some visual interest through either font (make sure it's readable), coloring, arrangement, or alignment so that the format enhances your resume and makes it easy to read.

Let me know if you have questions.
A
