### ISSUE TITLE
UXDI14 AnhThu, Le

### ISSUE THREAD

**Issue by anhthuple** [ga-dc/outcomes#110]
![le thu ux14 resume](https://user-images.githubusercontent.com/34451407/34700553-bde67fd8-f4b1-11e7-9703-d67fc84d6d38.png)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. No need to include your full address. City/state is sufficient.

2. Insert your brand statement just below your header. It's a strong way to introduce who you are and what you do.

3. Include descriptions for your experience sections. Give details about what you accomplished in each position. Be specific! 

4. Add UXDI to your experience section, listing your projects with it, at the top. PUt your UX experience right at the forefront instead of relegating it to the bottom.

Nice work! Let me know if you have questions.
A
