### ISSUE TITLE
Michael A. Brand Statement

### ISSUE THREAD

**Issue by michaelasaro** [ga-dc/outcomes#129]
Michael is an empathetic and systemic thinker who quickly identifies problems, and is organized and insightful when implementing solutions.

**Comment by allysonaustin** [comment]
Thanks for submitting!

Speak in first person. It comes across more confident and flows better on a resume/profile to talk as yourself, not about yourself.

Did you mean “systematic” instead of systemic? It’s technically correct, but an awkward way to use that word.

You might also consider adding a section at the end to describe the ends of these characteristics. What is the effect of being organized and insightful?

Be more specific - what kinds of problems are you passionate about solving?

Great work! Let me know if you have questions.
A
