### ISSUE TITLE
UXDI15 Rachel Morin- Draft Brand Statement

### ISSUE THREAD

**Issue by rmorin528** [ga-dc/outcomes#130]
Rachel is a fearless artist and global thinker eager to understand people and solve problems.

**Comment by allysonaustin** [comment]
Thanks for submitting!

Speak in first person. It comes across more confident and flows better on a resume/profile to talk as yourself, not about yourself.

I love the say your statement starts, but it loses momentum on the second half, and because it’s so brief it ends up falling flat really quickly. Combat this by more specifically describing the problems you solve, how you endeavor to understand people, and what is the ends or effects of these actions. End on as strong as note as the one that you started with!

Great work! Let me know if you have questions.
A
