### ISSUE TITLE
Jackie Loureiro Resume Draft

### ISSUE THREAD

**Issue by jackieloureiro** [ga-dc/outcomes#137]
[Resume - UX 2.pdf](https://github.com/ga-dc/outcomes/files/1915554/Resume.-.UX.2.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

Your brand statement starts very strongly, but then ends with what is essentially a summary of your resume. Since the reader is about to read all of this information, remove it from your brand statement and instead focus on articulating the parts of yourself that are unique - what distinguishes you from your colleagues in your class?

I encourage you to print your resume and make sure that the colors are dark enough to read.

Add your individual GA projects to your UXDI section to bolster your UX experience. It helps to show what you’ve accomplished.

Great work! Let me know if you have questions.
A
