### ISSUE TITLE
UXDI 15 Kristen Etzel draft resume

### ISSUE THREAD

**Issue by ketzel17** [ga-dc/outcomes#139]
[Etzel Resume 2018v2.pdf](https://github.com/ga-dc/outcomes/files/1917223/Etzel.Resume.2018v2.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

Swap your skills and education sections so that skills are closer to the top. Your skills are far more compelling!

In your UXDI section, list the skills you used to create each project. The name of the app doesn’t tell me much about it.

In your brand statement, hyphenate “human-centered.”

Some of your bullet points have periods at the end, and some do not. Choose one format and stick with it!

Great work! Let me know if you have questions.
A
