### ISSUE TITLE
UXDI 15 Linkedin and Resume Kristen Etzel

### ISSUE THREAD

**Issue by ketzel17** [ga-dc/outcomes#146]
https://www.linkedin.com/in/kristen-etzel-3744912a/

[Etzel Resume 2018v2.pdf](https://github.com/ga-dc/outcomes/files/1962034/Etzel.Resume.2018v2.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! In future, please double check the link for submission. This is not where homework should be submitted, and I will no longer be checking this repo.

I have just two comments for you.

1. I encourage you to put your UXDI projects as separate bullet points. They get a little lost as a paragraph, and it's more difficult to scan through quickly.

2. Your first sentence of your brand statement is a run-on sentence and doesn't quite make sense. Read it out loud and finesse the wording so that the sentence is complete.

Great work! Let me know if you have questions.
A
